### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by mikeygio10** [Swourire/AdminTroll-a-plugin-PocketMine-MP-#2]
i use it and after i use it it closeds my server crashes and it randomly does it i dont know why

**Comment by mikeygio10** [comment]
Hello????

**Comment by Swourire** [comment]
Can you describe the issue please, is it sending an error and are you using latest build ?

**Comment by mikeygio10** [comment]
Well when I tested on my alt used all of everything it worked great but then when I turned it offf using /admintroll it say server closed the. I check the crashed dumps and it crashed due to this plugin

**Comment by Swourire** [comment]
weird, I'll look into that

**Comment by mikeygio10** [comment]
well i did not try the verizon from 2 hours ago let me try that one

**Comment by Swourire** [comment]
It works fine for me, please try re-installing the plugin !

**Comment by mikeygio10** [comment]
yay your new verizon works thank you

**Comment by mikeygio10** [comment]
wait when the player leaves the server it closes it sorry lol

**Comment by Swourire** [comment]
Hmmm

**Comment by Swourire** [comment]
You have something that is doing that, mine is perfectly fine, tried to log when AdminTroll is enabled, and also tried with off, worked with both

**Comment by mikeygio10** [comment]
what verizon is the newest

**Comment by Swourire** [comment]
this one

**Comment by Swourire** [comment]
Fixed it in new version !
