### ISSUE TITLE
360º so slow

### ISSUE THREAD

**Issue by UnEnanoMas** [Swourire/AdminTroll-a-plugin-PocketMine-MP-#8]
Hey, welcome back after 5 years hahaha

I use the admintroll on my players and the 360º its so very very slow than previous updates

If u can make more faster was better for all i think xd

**Comment by Swourire** [comment]
thanks man, the 360 (faster) is available with the command /troll threesixty player multiplier
the multiplier will make the speed of it baseSpeed x multiplier :D
